### PR TITLE
Removed usage of eunit from `eredis_parser.erl`

### LINKED ISSUE #79: Compile issues with Elixir 1.15
When compiling with Elixir 1.15 we currently get the following error:

```
==> eredis
Compiling 6 files (.erl)
src/eredis_parser.erl:25:14: can't find include lib "eunit/include/eunit.hrl"
%   25| -include_lib("eunit/include/eunit.hrl").
%     |              ^
```

When setting `:prune_code_paths` to `false` in `mix.exs` it fixes the issue but according to the [release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.15.0) for Elixir 1.15.0 doing this may cause runtime bugs that only occur inside a `mix release`.

We are using Elixir 1.15.2 and Erlang 26.0.2.

### PR DESCRIPTION
**Pull request by anthonator**
This is causing compile time issues in Elixir 1.15.0. Seems like eunit isn't being used in this file so I removed it.

Fixes #79

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Rebar3 is broken for OTP 23. (Every time there is a new OTP version, rebar3 breaks old old OTP versions because they only support the last three versions, which are 24-25-26 now.) I've fixed it on master by installing an old rebar3 in the CI jobs where OTP 23 is used, so please rebase this on latest master.

**Comment by anthonator** [comment]
@zuiderkwast I updated my branch.

**Comment by zuiderkwast** [comment]
Thanks!

I still don't really get the Elixir error message, but it doesn't matter now. :-)

(I was surprised my commits appeared in the diff of your PR. Did you cherry-pick them? More common is to do git merge origin/master or git rebase origin/master. Anyways, after squash-merge everything is fine.)

**Comment by anthonator** [comment]
Thank you for taking care of this!

Any way we can get a new release?

**Comment by zuiderkwast** [comment]
OK, done. :-)

**Comment by anthonator** [comment]
Thank you!!!

**Pull request merged**
